id: I9AA08DB0
legacy_id: P007131
ocr_import_info:
  bdrc_scan_id: W5926
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:08:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:02:41.351404+00:00'
last_modified: 2022-09-04 11:04:58.152019
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5926
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW5926
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་དཔལ་ལྡན།
  author: ཁལ་ཁ་ངག་དབང་དཔལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.693190181510117
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I3833:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3833
      total_pages: 748
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3833.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6953253844025062
    legacy_id: v007
  I3832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3832
      total_pages: 706
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3832.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6797645305660155
    legacy_id: v006
  I3829:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3829
      total_pages: 606
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3829.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.67190211115813
    legacy_id: v003
  I3830:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3830
      total_pages: 714
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3830.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6959379042297356
    legacy_id: v004
  I3827:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3827
      total_pages: 658
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3827.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7269465323954292
    legacy_id: v001
  I3831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3831
      total_pages: 644
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3831.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6846002337386037
    legacy_id: v005
  I3828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3828
      total_pages: 622
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3828.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6933530174104646
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
