id: I9AA08DB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:14:49+00:00'
last_modified: '2022-06-09T06:19:04.526577+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5926
  title: གསུང་འབུམ། ངག་དབང་དཔལ་ལྡན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4DFB:
      image_group_id: I3827
      title: ''
      total_pages: 658
      order: 1
      base_file: 4DFB.txt
    BF5E:
      image_group_id: I3828
      title: ''
      total_pages: 622
      order: 2
      base_file: BF5E.txt
    '5150':
      image_group_id: I3829
      title: ''
      total_pages: 606
      order: 3
      base_file: 5150.txt
    44D6:
      image_group_id: I3830
      title: ''
      total_pages: 714
      order: 4
      base_file: 44D6.txt
    9A9D:
      image_group_id: I3831
      title: ''
      total_pages: 644
      order: 5
      base_file: 9A9D.txt
    CFD9:
      image_group_id: I3832
      title: ''
      total_pages: 706
      order: 6
      base_file: CFD9.txt
    2C98:
      image_group_id: I3833
      title: ''
      total_pages: 748
      order: 7
      base_file: 2C98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
