id: P007131
initial_creation_type: ocr
source_metadata:
  id: bdr:W5926
  title: གསུང་འབུམ། ངག་དབང་དཔལ་ལྡན
  author: ''
  volumes:
    2ebfb46b38454dfcba1d12fabed83edc:
      image_group_id: I3827
      title: ''
      volume_number: 1
      total_pages: 658
    8301e2f0b4b6433f99853bdb4169b325:
      image_group_id: I3828
      title: ''
      volume_number: 2
      total_pages: 622
    1ee88ee2df0b440e8049fc9904bcb9f2:
      image_group_id: I3829
      title: ''
      volume_number: 3
      total_pages: 606
    8a5bb52070b74cb58534f41942f0f842:
      image_group_id: I3830
      title: ''
      volume_number: 4
      total_pages: 714
    8f699722818f485f9d13a8df1399bbbb:
      image_group_id: I3831
      title: ''
      volume_number: 5
      total_pages: 644
    2e617e775f6e42fa863ff18a12c90639:
      image_group_id: I3832
      title: ''
      volume_number: 6
      total_pages: 706
    cd025b163fab4276b7f657aa1049f7f8:
      image_group_id: I3833
      title: ''
      volume_number: 7
      total_pages: 748
ebook_metadata:
  title: གསུང་འབུམ། ངག་དབང་དཔལ་ལྡན
  author: ''
  sku: P007131
  cover: cover.jpg
  layers:
  - pagination
